name: inventario_qa_app
description: "App móvil de Inventario QA (Flutter)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  http_parser: ^4.0.2
  go_router: ^14.6.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_form_builder: ^10.3.0
  form_builder_validators: ^11.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
